=== luisgg/xmlcopyeditor/src/dtd/moodle_glossary.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT GLOSSARY (INFO)>
<!ELEMENT INFO (NAME, INTRO, STUDENTCANPOST, ALLOWDUPLICATEDENTRIES, DISPLAYFORMAT, SHOWSPECIAL, SHOWALPHABET, SHOWALL, ALLOWCOMMENTS, USEDYNALINK, DEFAULTAPPROVAL, GLOBALGLOSSARY, ENTBYPAGE, ENTRIES)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT INTRO (#PCDATA)>
<!ELEMENT STUDENTCANPOST (#PCDATA)>
<!ELEMENT ALLOWDUPLICATEDENTRIES (#PCDATA)>
<!ELEMENT DISPLAYFORMAT (#PCDATA)>
<!ELEMENT SHOWSPECIAL (#PCDATA)>
<!ELEMENT SHOWALPHABET (#PCDATA)>
<!ELEMENT SHOWALL (#PCDATA)>
<!ELEMENT ALLOWCOMMENTS (#PCDATA)>
<!ELEMENT USEDYNALINK (#PCDATA)>
<!ELEMENT DEFAULTAPPROVAL (#PCDATA)>
<!ELEMENT GLOBALGLOSSARY (#PCDATA)>
<!ELEMENT ENTBYPAGE (#PCDATA)>
<!ELEMENT ENTRIES (ENTRY+)>
<!ELEMENT ENTRY (CONCEPT, DEFINITION, FORMAT, USEDYNALINK, CASESENSITIVE, FULLMATCH, TEACHERENTRY, ALIASES*, CATEGORIES)>
<!ELEMENT CONCEPT (#PCDATA)>
<!ELEMENT DEFINITION (#PCDATA)>
<!ELEMENT FORMAT (#PCDATA)>
<!ELEMENT CASESENSITIVE (#PCDATA)>
<!ELEMENT FULLMATCH (#PCDATA)>
<!ELEMENT TEACHERENTRY (#PCDATA)>
<!ELEMENT ALIASES (ALIAS+)>
<!ELEMENT ALIAS (NAME)>
<!ELEMENT CATEGORIES (CATEGORY)>
<!ELEMENT CATEGORY (NAME, USEDYNALINK)>

=== luisgg/xmlcopyeditor/src/templates/Moodle_glossary.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE GLOSSARY PUBLIC "-//Moodle Glossary//DTD" "moodle_glossary.dtd">
<GLOSSARY>
	<INFO>
		<NAME>String</NAME>
		<INTRO>String</INTRO>
		<STUDENTCANPOST>0</STUDENTCANPOST>
		<ALLOWDUPLICATEDENTRIES>0</ALLOWDUPLICATEDENTRIES>
		<DISPLAYFORMAT>String</DISPLAYFORMAT>
		<SHOWSPECIAL>0</SHOWSPECIAL>
		<SHOWALPHABET>0</SHOWALPHABET>
		<SHOWALL>0</SHOWALL>
		<ALLOWCOMMENTS>0</ALLOWCOMMENTS>
		<USEDYNALINK>0</USEDYNALINK>
		<DEFAULTAPPROVAL>0</DEFAULTAPPROVAL>
		<GLOBALGLOSSARY>0</GLOBALGLOSSARY>
		<ENTBYPAGE>0</ENTBYPAGE>
		<ENTRIES>
			<ENTRY>
				<CONCEPT>String</CONCEPT>
				<DEFINITION>String</DEFINITION>
				<FORMAT>0</FORMAT>
				<USEDYNALINK>0</USEDYNALINK>
				<CASESENSITIVE>0</CASESENSITIVE>
				<FULLMATCH>0</FULLMATCH>
				<TEACHERENTRY>0</TEACHERENTRY>
				<ALIASES>
					<ALIAS>
						<NAME>String</NAME>
					</ALIAS>
					<ALIAS>
						<NAME>String</NAME>
					</ALIAS>
				</ALIASES>
				<CATEGORIES>
					<CATEGORY>
						<NAME>String</NAME>
						<USEDYNALINK>0</USEDYNALINK>
					</CATEGORY>
				</CATEGORIES>
			</ENTRY>
			<ENTRY>
				<CONCEPT>String</CONCEPT>
				<DEFINITION>String</DEFINITION>
				<FORMAT>0</FORMAT>
				<USEDYNALINK>0</USEDYNALINK>
				<CASESENSITIVE>0</CASESENSITIVE>
				<FULLMATCH>0</FULLMATCH>
				<TEACHERENTRY>0</TEACHERENTRY>
				<ALIASES>
					<ALIAS>
						<NAME>String</NAME>
					</ALIAS>
				</ALIASES>
				<CATEGORIES>
					<CATEGORY>
						<NAME>String</NAME>
						<USEDYNALINK>0</USEDYNALINK>
					</CATEGORY>
				</CATEGORIES>
			</ENTRY>
		</ENTRIES>
	</INFO>
</GLOSSARY>
