=== luisgg/xmlcopyeditor/src/dtd/moodle_xml.dtd
<!ELEMENT answer (#PCDATA | feedback | fraction | text | tolerance)*>
<!ATTLIST answer
	fraction CDATA #IMPLIED
>
<!ELEMENT correctfeedback (text)>
<!ELEMENT defaultgrade (#PCDATA)>
<!ELEMENT feedback (text)>
<!ELEMENT fraction (#PCDATA)>
<!ELEMENT generalfeedback (text)>
<!ELEMENT hidden (#PCDATA)>
<!ELEMENT image EMPTY>
<!ELEMENT incorrectfeedback (text)>
<!ELEMENT name (text)>
<!ELEMENT partiallycorrectfeedback (text)>
<!ELEMENT penalty (#PCDATA)>
<!ELEMENT question (name | questiontext | image | generalfeedback | defaultgrade | penalty | hidden | shuffleanswers | answer | subquestion | single | correctfeedback | incorrectfeedback | partiallycorrectfeedback | usecase)+>
<!ATTLIST question
	type (multichoice|truefalse|shortanswer|match|cloze|essay|numerical|description) #REQUIRED
>
<!ELEMENT questiontext (text)>
<!ATTLIST questiontext
	format (moodle_auto_format|html|plain_text|markdown) #REQUIRED
>
<!ELEMENT quiz (question+)>
<!ELEMENT shuffleanswers (#PCDATA)>
<!ELEMENT single (#PCDATA)>
<!ELEMENT subquestion (text, answer)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT tolerance (#PCDATA)>
<!ELEMENT usecase (#PCDATA)>

=== luisgg/xmlcopyeditor/src/templates/Moodle_quiz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE quiz PUBLIC "-//Moodle XML//DTD" "moodle_xml.dtd">
<quiz>
  <question type="multichoice">
    <name>
      <text>Name</text>
    </name>
    <questiontext format="html">
      <text>Question</text>
    </questiontext>
    <image/>
    <generalfeedback>
      <text/>
    </generalfeedback>
    <defaultgrade>1</defaultgrade>
    <penalty>0.1</penalty>
    <hidden>0</hidden>
    <shuffleanswers>1</shuffleanswers>
    <single>true</single>
    <shuffleanswers>true</shuffleanswers>
    <correctfeedback>
      <text/>
    </correctfeedback>
    <partiallycorrectfeedback>
      <text/>
    </partiallycorrectfeedback>
    <incorrectfeedback>
      <text/>
    </incorrectfeedback>
    <answer fraction="0">
      <text>Option A</text>
      <feedback>
        <text>
          </text>
      </feedback>
    </answer>
    <answer fraction="0">
      <text>Option B</text>
      <feedback>
        <text>
          </text>
      </feedback>
    </answer>
    <answer fraction="0">
      <text>Option C</text>
      <feedback>
        <text>
          </text>
      </feedback>
    </answer>
    <answer fraction="100">
      <text>Option D</text>
      <feedback>
        <text>
          </text>
      </feedback>
    </answer>
  </question>
</quiz>
