=== luisgg/xmlcopyeditor/src/rulesets/ruleset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<!-- ruleset -->
  <xs:element name="ruleset">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="copyright" type="xs:string" minOccurs="0"/>
        <xs:element name="exclude" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="include" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="rule" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<!-- rule -->
  <xs:element name="rule">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="report" type="xs:string"/>
        <xs:choice>
          <xs:element ref="regex"/>
          <xs:element ref="dictionary"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<!-- regex -->
  <xs:element name="regex">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="find"/>
        <xs:element ref="replace"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<!-- find -->
  <xs:element name="find">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="matchcase" type="xs:boolean" use="optional" default="false"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
<!-- replace -->
  <xs:element name="replace">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="adjustcase" type="xs:boolean" use="optional" default="false"/>
          <xs:attribute name="tentative" type="xs:boolean" use="optional" default="false"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
<!-- dictionary -->
  <xs:element name="dictionary">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="term" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<!-- term -->
  <xs:element name="term">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="passive" type="xs:boolean" use="optional" default="false"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== luisgg/xmlcopyeditor/src/rulesets/Contractions.xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ruleset.xsd">
  <title>Contractions</title>
  <rule>
    <report>she would (not she’d)</report>
    <regex>
      <find>\b(s?he|it|that|they|we|what|who)(?:'|’)(d)\b</find>
      <replace adjustcase="true" tentative="true">\1 woul\2</replace>
    </regex>
  </rule>
  <rule>
    <report>she will (not she’ll)</report>
    <regex>
      <find>\b(s?he|it|that|they|we|what|who)(?:'|’)(ll)\b</find>
      <replace adjustcase="true" tentative="true">\1 wi\2</replace>
    </regex>
  </rule>
  <rule>
    <report>she is (not she’s)</report>
    <regex>
      <find>\b(s?he|it|that|what|who)(?:'|’)(s)\b</find>
      <replace adjustcase="true" tentative="true">\1 i\2</replace>
    </regex>
  </rule>
  <rule>
    <report>we are (not we’re)</report>
    <regex>
      <find>\b(we|you|they)(?:'|’)(re)\b</find>
      <replace adjustcase="true" tentative="true">\1 a\2</replace>
    </regex>
  </rule>
  <rule>
    <report>are not (not aren’t)</report>
    <regex>
      <find>\b(\w+)(?&lt;!ca|sha|wo)(n)(?:'|’)(t)\b</find>
      <replace adjustcase="true" tentative="true">\1 \2o\3</replace>
    </regex>
  </rule>
  <rule>
    <report>cannot (not can’t)</report>
    <regex>
      <find>\b(can)(?:'|’)(t)\b</find>
      <replace adjustcase="true" tentative="true">\1no\2</replace>
    </regex>
  </rule>
  <rule>
    <report>shall not (not shan’t)</report>
    <regex>
      <find>\b(sha)(n)(?:'|’)(t)\b</find>
      <replace adjustcase="true" tentative="true">\1ll \2o\3</replace>
    </regex>
  </rule>
  <rule>
    <report>will not (not won’t)</report>
    <regex>
      <find>\b(w)(o)(n)(?:'|’)(t)\b</find>
      <replace adjustcase="true" tentative="true">\1ill \3\2\4</replace>
    </regex>
  </rule>
</ruleset>

=== luisgg/xmlcopyeditor/src/rulesets/American.xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ruleset.xsd">
  <title>American spelling</title>
  <include>Ize.xml</include>
  <rule>
    <report>acknowledgment, judgment</report>
    <regex>
      <find>\b((?:acknowle|ju)dg)e(ments?)\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>eon</report>
    <regex>
      <find>\ba(eons?)\b</find>
      <replace adjustcase="true">\1</replace>
    </regex>
  </rule>
  <rule>
    <report>esthetic, feces, hemoglobin</report>
    <regex>
      <find>\b(|f|h)a(esthetic|eces|emoglobin)\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>aluminum</report>
    <regex>
      <find>\b(alumin)i(um)\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>ameba, diarrhea, fetus, esophagus</report>
    <regex>
      <find>\b(|am|diarrh|f)o(e(?:a|tus|sophag(?:i|us)))\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>analog, catalog, dialog</report>
    <regex>
      <find>\b((?:ana|cata|dia)log)ue(s?)\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>anesthesia</report>
    <regex>
      <find>\b(an)a(esthe(?:sia|tic))\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>annex, ax, furor, glycerin</report>
    <regex>
      <find>\b(annex|ax|furor|glycerin)e\b</find>
      <replace>\1</replace>
    </regex>
  </rule>
  <rule>
    <report>appall, distill, enroll, fulfill, instill</report>
    <regex>
      <find>\b((appa|disti|enro|fulfi|insti)l)\b</find>
      <replace adjustcase="true">\1l</replace>
    </regex>
  </rule>
  <rule>
    <report>archeology</report>
    <regex>
      <find>\b(arch)a(eolog(?:ical(|ly)|ists?|y))\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>armor, color, etc.</report>
    <regex>
      <find>\b((?:arm|col|fl?av|hon|hum|lab|neighb|splend)o)u(r(?:|abl[ey]|ed|hood|ing|s))\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>artifact</report>
    <regex>
      <find>\b(art)e(facts?)\b</find>
      <replace adjustcase="true">\1i\2</replace>
    </regex>
  </rule>
  <rule>
    <report>channeling, leveling, etc.</report>
    <regex>
      <find>\b((?:cance|channe|counce|disheve|equa|leve|riva|signa|trave)l)l(ed|ers?|ing|or)\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>carburetor</report>
    <regex>
      <find>\b(carburet)t(ors?)\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>center</report>
    <regex>
      <find>([a-z]*cent)re\b</find>
      <replace adjustcase="true">\1er\2</replace>
    </regex>
  </rule>
  <rule>
    <report>centered</report>
    <regex>
      <find>([a-z]*cent)re(d)\b</find>
      <replace adjustcase="true">\1ere\2</replace>
    </regex>
  </rule>
  <rule>
    <report>centering</report>
    <regex>
      <find>\b(cent)(ring)\b</find>
      <replace adjustcase="true">\1e\2</replace>
    </regex>
  </rule>
  <rule>
    <report>connexion, inflexion, reflexion</report>
    <regex>
      <find>\b((?:conn|infl|refl)e)ct(ions?)\b</find>
      <replace adjustcase="true">\1x\2</replace>
    </regex>
  </rule>
  <rule>
    <report>cozy</report>
    <regex>
      <find>\b(co)s(ie(?:r|st)|y)\b</find>
      <replace adjustcase="true">\1z\2</replace>
    </regex>
  </rule>
  <rule>
    <report>defense, offense, pretense</report>
    <regex>
      <find>\b((?:defe|offe|prete)n)c(e(?:|less|s))\b</find>
      <replace adjustcase="true">\1s\2</replace>
    </regex>
  </rule>
  <rule>
    <report>Fall</report>
    <regex>
      <find matchcase="true">\bAutumn\b</find>
      <replace>Fall</replace>
    </regex>
  </rule>
  <rule>
    <report>fiber, saber, specter, theater</report>
    <regex>
      <find>\b((?:(?:fi|sa)b|spect|theat))re(s?)\b</find>
      <replace adjustcase="true">\1er\2</replace>
    </regex>
  </rule>
  <rule>
    <report>fontanel</report>
    <regex>
      <find>\b(fontanel)le\b</find>
      <replace>\1</replace>
    </regex>
  </rule>
  <rule>
    <report>glamor, savior</report>
    <regex>
      <find>\b((?:glam|savi)o)u(r[a-z]*)\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>good-by</report>
    <regex>
      <find>\b(good-by)e\b</find>
      <replace>\1</replace>
    </regex>
  </rule>
  <rule>
    <report>gray</report>
    <regex>
      <find>\b(gr)e(ys?)\b</find>
      <replace adjustcase="true">\1a\2</replace>
    </regex>
  </rule>
  <rule>
    <report>jail</report>
    <regex>
      <find>\bg(a)o(l)(s?)</find>
      <replace adjustcase="true">j\1i\2\3</replace>
    </regex>
  </rule>
  <rule>
    <report>jewelry</report>
    <regex>
      <find>\b(jewel)le(ry)\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>jeweled</report>
    <regex>
      <find>\b(jewel)l(ed)\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>kidnaper, worshiper</report>
    <regex>
      <find>\b((?:kidna|worshi)p)p(ed|er|ing)\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>license</report>
    <regex>
      <find>\b(licen)c(e(?:|e|d))\b</find>
      <replace adjustcase="true">\1s\2</replace>
    </regex>
  </rule>
  <rule>
    <report>meter, centimeter, kilometer, millimeter</report>
    <regex>
      <find>\b((?:|centi|kilo|milli)met)re(s?)\b</find>
      <replace adjustcase="true">\1er\2</replace>
    </regex>
  </rule>
  <rule>
    <report>maneuver</report>
    <regex>
      <find>\b(man)oe(uv)re(|[ds])\b</find>
      <replace adjustcase="true">\1e\2er\3</replace>
    </regex>
  </rule>
  <rule>
    <report>maneuvering</report>
    <regex>
      <find>\b(man)oe(uv)(ring)\b</find>
      <replace adjustcase="true">\1e\2e\3</replace>
    </regex>
  </rule>
  <rule>
    <report>mold</report>
    <regex>
      <find>\b(mo)u(ld(?:|ed|ing|s))\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>plow</report>
    <regex>
      <find>\b(plo)ugh(|ed|ing|s)\b</find>
      <replace adjustcase="true">\1w\2</replace>
    </regex>
  </rule>
  <rule>
    <report>mustache</report>
    <regex>
      <find>\b(m)o(ustaches?)\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>pajamas</report>
    <regex>
      <find>\b(p)y(jama(?:|s))\b</find>
      <replace adjustcase="true">\1a\2</replace>
    </regex>
  </rule>
  <rule>
    <report>practice</report>
    <regex>
      <find>\b(practi)s(e(?:|d)|ing)\b</find>
      <replace>\1c\2</replace>
    </regex>
  </rule>
  <rule>
    <report>railroad</report>
    <regex>
      <find>\b(rail)way(s?)\b</find>
      <replace adjustcase="true">\1road\2</replace>
    </regex>
  </rule>
  <rule>
    <report>skeptical</report>
    <regex>
      <find>\b(s)c(eptic(?:|ism|s|al))\b</find>
      <replace adjustcase="true">\1k\2</replace>
    </regex>
  </rule>
  <rule>
    <report>skillful, willful</report>
    <regex>
      <find>\b((?:|un)(?:ski|wi)l)(ful(?:|ly))\b</find>
      <replace adjustcase="true">\1l\2</replace>
    </regex>
  </rule>
  <rule>
    <report>sulfur</report>
    <regex>
      <find>\b(sul)ph(ate|ite|ur(?:|etted))\b</find>
      <replace adjustcase="true">\1f\2</replace>
    </regex>
  </rule>
  <rule>
    <report>woolen</report>
    <regex>
      <find>\b(wool)l(en)\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
</ruleset>

=== luisgg/xmlcopyeditor/src/rulesets/Punctuation.xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ruleset.xsd">
  <title>Punctuation</title>
  <rule>
    <report>1–2</report>
    <regex>
      <find>\b(\d+)(?:-|—)(\d+)\b</find>
      <replace tentative="true">\1–\2</replace>
    </regex>
  </rule>
  <rule>
    <report>13–14</report>
    <regex>
      <find>\b(\d*)(1)(\d)–(\d)\b</find>
      <replace>\1\2\3–\2\4</replace>
    </regex>
  </rule>
  <rule>
    <report>leave space after comma, semicolon and colon</report>
    <regex>
      <find>([,;:])([a-z]+)</find>
      <replace>\1 \2</replace>
    </regex>
  </rule>
  <rule>
    <report>one space only after punctuation marks</report>
    <regex>
      <find>([\.;:]) {2,}(\w+)</find>
      <replace>\1 \2</replace>
    </regex>
  </rule>
  <rule>
    <report>no space before comma, semicolon and colon</report>
    <regex>
      <find> ([,;:])</find>
      <replace>\1</replace>
    </regex>
  </rule>
  <rule>
    <report>use en-rule between spaces</report>
    <regex>
      <find> (?:-|—) </find>
      <replace> – </replace>
    </regex>
  </rule>
</ruleset>

=== luisgg/xmlcopyeditor/src/rulesets/Ethnicity.xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ruleset.xsd">
  <title>Ethnicity</title>
  <rule>
    <report>Inuit</report>
    <regex>
      <find>\beskimo(s?)\b</find>
      <replace adjustcase="true" tentative="true">Inuit\1</replace>
    </regex>
  </rule>
  <rule>
    <report>Native American</report>
    <regex>
      <find>\b:red indian(s?)\b</find>
      <replace tentative="true">Native American\1</replace>
    </regex>
  </rule>
</ruleset>

=== luisgg/xmlcopyeditor/src/rulesets/Religion.xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ruleset.xsd">
  <title>Religion</title>
  <rule>
    <report>Buddhism</report>
    <regex>
      <find matchcase="true">\bb(uddh(?:is[mt]))\b</find>
      <replace tentative="true">B\1</replace>
    </regex>
  </rule>
  <rule>
    <report>Christianity</report>
    <regex>
      <find matchcase="true">\bc(hristian(?:|ity|s))\b</find>
      <replace tentative="true">C\1</replace>
    </regex>
  </rule>
  <rule>
    <report>Hinduism</report>
    <regex>
      <find matchcase="true">\bh(indu(?:|ism|s))\b</find>
      <replace tentative="true">H\1</replace>
    </regex>
  </rule>
  <rule>
    <report>Islam</report>
    <regex>
      <find matchcase="true">\bi(slam(?:|ic|is[mt]))\b</find>
      <replace tentative="true">I\1</replace>
    </regex>
  </rule>
  <rule>
    <report>Judaism</report>
    <regex>
      <find matchcase="true">\bj(udai(?:c|sm))\b</find>
      <replace tentative="true">J\1</replace>
    </regex>
  </rule>
  <rule>
    <report>Rastafarianism</report>
    <regex>
      <find matchcase="true">\br(astafarian(?:|ism|s))\b</find>
      <replace tentative="true">R\1</replace>
    </regex>
  </rule>
  <rule>
    <report>Sikhism</report>
    <regex>
      <find matchcase="true">\bs(ikh(?:|ism))\b</find>
      <replace tentative="true">S\1</replace>
    </regex>
  </rule>
  <rule>
    <report>Muslim</report>
    <regex>
      <find>\bmohammedan\b</find>
      <replace tentative="true">Muslim</replace>
    </regex>
  </rule>
</ruleset>

=== luisgg/xmlcopyeditor/src/rulesets/Commonwealth.xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ruleset.xsd">
  <title>Commonwealth spelling</title>
  <include>Ise.xml</include>
  <rule>
    <report>acknowledgement</report>
    <regex>
      <find>\b(acknowledg)(ments?)\b</find>
      <replace adjustcase="true">\1e\2</replace>
    </regex>
  </rule>
  <rule>
    <report>analogue, catalogue, dialogue</report>
    <regex>
      <find>\b(ana|cata|dia)(log)(|s)\b</find>
      <replace adjustcase="true">\1\2ue\3</replace>
    </regex>
  </rule>
  <rule>
    <report>anaesthesia</report>
    <regex>
      <find>\b(an)(esthe(?:sia|tic))\b</find>
      <replace adjustcase="true">\1a\2</replace>
    </regex>
  </rule>
  <rule>
    <report>annexe, axe, furore, glycerine</report>
    <regex>
      <find>\b(annex|ax|furor|glycerin)\b</find>
      <replace adjustcase="true">\1e</replace>
    </regex>
  </rule>
  <rule>
    <report>appal, distil, enrol, instil</report>
    <regex>
      <find>\b(appa|disti|enro|insti)(l)l\b</find>
      <replace adjustcase="true">\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>archaeology</report>
    <regex>
      <find>\b(arch)(eolog(?:ical(?:|ly)|ists?|y))\b</find>
      <replace adjustcase="true">\1a\2</replace>
    </regex>
  </rule>
  <rule>
    <report>armour, colour, etc.</report>
    <regex>
      <find>\b(arm|col|fl?av|hon|hum|lab|neighb|splend)(o)(r)(|abl[ey]|ed|hood|ing|s)\b</find>
      <replace adjustcase="true">\1\2u\3\4</replace>
    </regex>
  </rule>
  <rule>
    <report>aluminium</report>
    <regex>
      <find>\b(alumin)(um)\b</find>
      <replace adjustcase="true">\1i\2</replace>
    </regex>
  </rule>
  <rule>
    <report>amoeba, diarrhoea, foetus, oesophagus</report>
    <regex>
      <find>\b(|am|diarrh|f)(e)(a|ba(?:|s)|tus(?:|es)|sophag(?:i|us))\b</find>
      <replace adjustcase="true">\1o\2\3</replace>
    </regex>
  </rule>
  <rule>
    <report>artefact</report>
    <regex>
      <find>\b(art)i(facts?)\b</find>
      <replace adjustcase="true">\1e\2</replace>
    </regex>
  </rule>
  <rule>
    <report>channelling, levelling, etc.</report>
    <regex>
      <find>\b(cance|channe|counce|disheve|equa|leve|riva|signa|trave)(l)(ed|ers?|ing|or)\b</find>
      <replace adjustcase="true">\1\2l\3</replace>
    </regex>
  </rule>
  <rule>
    <report>carburettor</report>
    <regex>
      <find>\b(carburet)(ors?)\b</find>
      <replace adjustcase="true">\1t\2</replace>
    </regex>
  </rule>
  <rule>
    <report>centre</report>
    <regex>
      <find>(cent)er(|ing|ed)\b</find>
      <replace adjustcase="true">\1re\2</replace>
    </regex>
  </rule>
  <rule>
    <report>centimetre, kilometre, millimetre</report>
    <regex>
      <find>\b((?:centi|kilo|milli)met)er(s?)\b</find>
      <replace adjustcase="true">\1re\2</replace>
    </regex>
  </rule>
  <rule>
    <report>cigarette</report>
    <regex>
      <find>\b(cigaret)(s?)\b</find>
      <replace adjustcase="true">\1te\2</replace>
    </regex>
  </rule>
  <rule>
    <report>connection, inflection, reflection</report>
    <regex>
      <find>\b((?:conn|infl|refl)e)x(ions?)\b</find>
      <replace adjustcase="true">\1ct\2</replace>
    </regex>
  </rule>
  <rule>
    <report>cosy</report>
    <regex>
      <find>\b(co)z(y)\b</find>
      <replace adjustcase="true">\1s\2</replace>
    </regex>
  </rule>
  <rule>
    <report>defence, offence, pretence</report>
    <regex>
      <find>\b((?:defe|offe|prete)n)s(es?)\b</find>
      <replace adjustcase="true">\1c\2</replace>
    </regex>
  </rule>
  <rule>
    <report>aesthetic, faeces, haemoglobin</report>
    <regex>
      <find>\b(|f|h)(e)(sthetic|ces|moglobin)\b</find>
      <replace adjustcase="true">\1a\2\3</replace>
    </regex>
  </rule>
  <rule>
    <report>aeon</report>
    <regex>
      <find>\b(eons?)\b</find>
      <replace adjustcase="true">a\1</replace>
    </regex>
  </rule>
  <rule>
    <report>fibre, sabre, spectre, theatre</report>
    <regex>
      <find>\b((?:fi|sa)b|spect|theat)er(s?)\b</find>
      <replace adjustcase="true">\1re\2</replace>
    </regex>
  </rule>
  <rule>
    <report>fontanelle</report>
    <regex>
      <find>\b(fontanel)\b</find>
      <replace adjustcase="true">\1le</replace>
    </regex>
  </rule>
  <rule>
    <report>fulfil</report>
    <regex>
      <find>\b(fulfil)l(|s|ments?)\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>glamour, saviour</report>
    <regex>
      <find>\b((?:glam|savi)o)(r[a-z]*)\b</find>
      <replace adjustcase="true">\1u\2</replace>
    </regex>
  </rule>
  <rule>
    <report>good-bye</report>
    <regex>
      <find>\b(good-by)\b</find>
      <replace adjustcase="true">\1e</replace>
    </regex>
  </rule>
  <rule>
    <report>grey</report>
    <regex>
      <find>\b(gr)a(ys?)\b</find>
      <replace adjustcase="true">\1e\2</replace>
    </regex>
  </rule>
  <rule>
    <report>jewelled</report>
    <regex>
      <find>\b(jewel)(ed)\b</find>
      <replace adjustcase="true">\1l\2</replace>
    </regex>
  </rule>
  <rule>
    <report>jewellery</report>
    <regex>
      <find>\b(jewel)(ry)\b</find>
      <replace adjustcase="true">\1le\2</replace>
    </regex>
  </rule>
  <rule>
    <report>kidnapper, worshipper</report>
    <regex>
      <find>\b(kidna|worshi)(p)(ed|er|ing)\b</find>
      <replace>\1\2\2\3</replace>
    </regex>
  </rule>
  <rule>
    <report>licence</report>
    <regex>
      <find>\b(licen)s(e(?:|d|e))\b</find>
      <replace adjustcase="true">\1c\2</replace>
    </regex>
  </rule>
  <rule>
    <report>manoeuvre</report>
    <regex>
      <find>\b(man)(euv)er(|ed|s)\b</find>
      <replace adjustcase="true">\1o\2re\3</replace>
    </regex>
  </rule>
  <rule>
    <report>manoeuvring</report>
    <regex>
      <find>\b(man)(euv)er(ing)\b</find>
      <replace adjustcase="true">\1o\2r\3</replace>
    </regex>
  </rule>
  <rule>
    <report>mould</report>
    <regex>
      <find>\b(mo)(ld)(|ed|ing|s)\b</find>
      <replace adjustcase="true">\1u\2\3</replace>
    </regex>
  </rule>
  <rule>
    <report>plough</report>
    <regex>
      <find>\b(plo)w(|ed|ing|s)\b</find>
      <replace adjustcase="true">\1ugh\2</replace>
    </regex>
  </rule>
  <rule>
    <report>moustache</report>
    <regex>
      <find>\b(m)(ustaches?)\b</find>
      <replace adjustcase="true">\1o\2</replace>
    </regex>
  </rule>
  <rule>
    <report>pyjamas</report>
    <regex>
      <find>\b(p)a(jama(?:|s))\b</find>
      <replace adjustcase="true">\1y\2</replace>
    </regex>
  </rule>
  <rule>
    <report>railway</report>
    <regex>
      <find>\b(rail)road(s?)\b</find>
      <replace adjustcase="true">\1way\2</replace>
    </regex>
  </rule>
  <rule>
    <report>sceptical</report>
    <regex>
      <find>\b(s)k(eptic(?:|ism|s|al))\b</find>
      <replace adjustcase="true">\1c\2</replace>
    </regex>
  </rule>
  <rule>
    <report>skilful, wilful</report>
    <regex>
      <find>\b((?:|un)(?:ski|wi)l)l(ful(?:|ly))\b</find>
      <replace>\1\2</replace>
    </regex>
  </rule>
  <rule>
    <report>sulphur</report>
    <regex>
      <find>\b(sul)f(ate|ite|ur(?:|etted))\b</find>
      <replace adjustcase="true">\1ph\2</replace>
    </regex>
  </rule>
  <rule>
    <report>woollen</report>
    <regex>
      <find>\b(woo)(l)(en)\b</find>
      <replace adjustcase="true">\1\2\2\3</replace>
    </regex>
  </rule>
</ruleset>

=== luisgg/xmlcopyeditor/src/rulesets/Postcolonial.xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ruleset.xsd">
  <title>Post-colonial</title>
  <rule>
    <report>Mumbai (not Bombay)</report>
    <regex>
      <find>\bBombay\b</find>
      <replace tentative="true">Mumbai</replace>
    </regex>
  </rule>
  <rule>
    <report>Chennai (not Madras)</report>
    <regex>
      <find>\bMadras\b</find>
      <replace tentative="true">Chennai</replace>
    </regex>
  </rule>
  <rule>
    <report>Thiruvananthapuram (not Trivandrum)</report>
    <regex>
      <find>\bTrivandrum\b</find>
      <replace tentative="true">Thiruvananthapuram</replace>
    </regex>
  </rule>
  <rule>
    <report>Kozhikode (not Calicut)</report>
    <regex>
      <find>\bCalicut\b</find>
      <replace tentative="true">Kozhikode</replace>
    </regex>
  </rule>
  <rule>
    <report>Kochi (not Cochin)</report>
    <regex>
      <find>\bCochin\b</find>
      <replace tentative="true">Kochi</replace>
    </regex>
  </rule>
  <rule>
    <report>Koyamutthoor (not Coimbatore)</report>
    <regex>
      <find>\bCoimbatore\b</find>
      <replace tentative="true">Koyamutthoor</replace>
    </regex>
  </rule>
  <rule>
    <report>Puduchchery (not Pondicherry)</report>
    <regex>
      <find>\bPondicherry\b</find>
      <replace tentative="true">Puduchchery</replace>
    </regex>
  </rule>
  <rule>
    <report>Kolkata (not Calcutta)</report>
    <regex>
      <find>\bCalcutta\b</find>
      <replace tentative="true">Kolkata</replace>
    </regex>
  </rule>
</ruleset>

=== luisgg/xmlcopyeditor/src/rulesets/Ize_and_yse.xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ruleset.xsd">
  <title>-ize and -yse</title>
  <rule>
    <report>-ize</report>
    <regex>
      <find>\b([a-z]+)(?:(?&lt;=ic|[ai]m|[^a-z]pr|[eiou][tr])|(?&lt;![rd]a|c|gu|m|parad|o|p|r|[acrs]t|v|w))(i)s(a(?:bl[ey]|tion(?:|al(?:|ly)|s))|e|ed|ers?|(?&lt;!ys)es|ing)\b</find>
      <replace adjustcase="true">\1\2z\3</replace>
    </regex>
  </rule>
  <rule>
    <report>-yse</report>
    <regex>
      <find>\b([a-z]+)(?:(?&lt;=emphas|fantas)|(?&lt;!ba|ma|pr|se|s))(y)z(a(?:bl[ey]|tion(?:|al(?:|ly)|s))|es?|ed|ers?|ing)\b</find>
      <replace adjustcase="true">\1\2s\3</replace>
    </regex>
  </rule>
</ruleset>
