=== luisgg/xmlcopyeditor/src/rulesets/ruleset.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<!-- ruleset -->
  <xs:element name="ruleset">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="copyright" type="xs:string" minOccurs="0"/>
        <xs:element name="exclude" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="include" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="rule" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<!-- rule -->
  <xs:element name="rule">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="report" type="xs:string"/>
        <xs:choice>
          <xs:element ref="regex"/>
          <xs:element ref="dictionary"/>
        </xs:choice>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<!-- regex -->
  <xs:element name="regex">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="find"/>
        <xs:element ref="replace"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<!-- find -->
  <xs:element name="find">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="matchcase" type="xs:boolean" use="optional" default="false"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
<!-- replace -->
  <xs:element name="replace">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="adjustcase" type="xs:boolean" use="optional" default="false"/>
          <xs:attribute name="tentative" type="xs:boolean" use="optional" default="false"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
<!-- dictionary -->
  <xs:element name="dictionary">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="term" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<!-- term -->
  <xs:element name="term">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="passive" type="xs:boolean" use="optional" default="false"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== luisgg/xmlcopyeditor/src/rulesets/Gender.xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ruleset.xsd">
  <title>Gender</title>
  <rule>
    <report>author, mayor, manager, poet</report>
    <regex>
      <find>\b((?:auth|may)or|manager|poet)ess\b</find>
      <replace tentative="true">\1</replace>
    </regex>
  </rule>
  <rule>
    <report>actor, sculptor</report>
    <regex>
      <find>\b(act|sculpt)ress\b</find>
      <replace adjustcase="true" tentative="true">\1or</replace>
    </regex>
  </rule>
  <rule>
    <report>flight attendant (not stewardess)</report>
    <regex>
      <find>\bstewardesse?(s?)\b</find>
      <replace adjustcase="true" tentative="true">flight attendant\1</replace>
    </regex>
  </rule>
  <rule>
    <report>phrases to avoid</report>
    <regex>
      <find>\b(?:best man for the job|man in the street|man to man|no man's land|one[- ]man show|every man for himself)\b</find>
      <replace tentative="true">---</replace>
    </regex>
  </rule>
  <rule>
    <report>chair (not chairman), firefighter (not fireman), etc.</report>
    <regex>
      <find>\b(?:air(?:|craft)|anchor|bar|boat|business|chair|congress|council|door|dust|Dutch|English|French|fire|fresh|lay|mail|middle|militia|milk|news(?:|paper)|police|post|press|spokes|Ulster|weather)m[ae]n\b</find>
      <replace tentative="true">---</replace>
    </regex>
  </rule>
  <rule>
    <report>fair play (not sportsmanship), skill (not craftsmanship), etc.</report>
    <regex>
      <find>\b(?:brink|crafts|draughts|horse|pen|sea|show|sports|works)manship\b</find>
      <replace tentative="true">---</replace>
    </regex>
  </rule>
  <rule>
    <report>fair (not sportsmanlike)</report>
    <regex>
      <find>\b(?:|un)sportsmanlike\b</find>
      <replace tentative="true">---</replace>
    </regex>
  </rule>
  <rule>
    <report>humankind</report>
    <regex>
      <find>\b(mankind)\b</find>
      <replace adjustcase="true" tentative="true">hu\1</replace>
    </regex>
  </rule>
  <rule>
    <report>artificial (not man-made)</report>
    <regex>
      <find>\bman-made\b</find>
      <replace adjustcase="true" tentative="true">artificial</replace>
    </regex>
  </rule>
  <rule>
    <report>working hours (not manhours), etc.</report>
    <regex>
      <find>\bman(?:hours|hunt|power)\b</find>
      <replace tentative="true">---</replace>
    </regex>
  </rule>
</ruleset>

=== luisgg/xmlcopyeditor/src/rulesets/Query.xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ruleset.xsd">
  <title>Query</title>
  <rule>
    <report>unresolved</report>
    <regex>
      <find>\?\?+</find>
      <replace tentative="true">---</replace>
    </regex>
  </rule>
  <rule>
    <report>word containing question mark</report>
    <regex>
      <find>(\w+)?\?\w+</find>
      <replace tentative="true">---</replace>
    </regex>
  </rule>
</ruleset>

=== luisgg/xmlcopyeditor/src/rulesets/Repetition.xml
<?xml version="1.0" encoding="UTF-8"?>
<ruleset xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ruleset.xsd">
  <title>Repetition</title>
  <rule>
    <report>one word</report>
    <regex>
      <find>\b(\w+) \1\b</find>
      <replace tentative="true">\1</replace>
    </regex>
  </rule>
  <rule>
    <report>two words</report>
    <regex>
      <find>\b(\w+ \w+) \1\b</find>
      <replace tentative="true">\1</replace>
    </regex>
  </rule>
</ruleset>
